version: '3'
services:
  mysite:
    build: ./server
    ports:
      - "8000:8000" 
    tty: true
    volumes:
      - ./server:/app
  app:
    build: ./src
    ports:
      - "3000:3000"
    tty: true
    volumes:
      - ./src:/app